service: komodo-aws-blast-control

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  activation:
    handler: handler.activation
    events:
      - http:
          path: activation
          method: get
